travis:
  secure:
    BINSTAR_TOKEN: V0ZqAouLYC3auEKWVjsDzDovK3J0YX/o9ZR0e8XpEwJp338Gg3cy6wbTlLSxdKnqFZU1hk23ZEVgUSfAzA4xmUKXzLDWzBddsdFy1ONConGDMvsJXMqZWo0knl16jndkl8dny4YZBiCpXU8ZflupPF/vRhXc3FnTitL+hGSBz30HmNm//ciSXELg3fUS1Tze6Khm/Cx1x6O8YNLO0/GJtXVH0U4angNd4a2zrfAFqyYlD1lBv8ADYzSbPaBhVHTd9vIvx4PMKMwvqdxDE5XzItx1SmMn3WRuzo6s5cLc+hl+tqEH+WFLFYgNRSJRRcvvisk0+gJkZtf2tKXPUaTTEZvnycME4op0CIM+ungATubtnGnfQ4ICkk6aY0czclpBHibfVnosOkgTSde108ZosMdbUYTz/2eAVxVoKJbrT9irGobo+fnMHkbHLQD3OHNySAPImCfb7iJoS5TN7WK7nqNlG4QNLkwvj7LTIG7hpkmuF/o+tDm3p38KHaVtD0Db0CUQxsVOTTmcicmnNYrMLvA45ngIf/l+2IKOYVD/IUIAaqgNv6owbmw0mZn/dRFcnYx7QCbJNsa6XAExB8rQO7kjn9tVH5+tieFJQkmsNwEbWzgSMD2j1o8JYb0PnjTBvMm81fsJYzXEX0qIqWnFHEkWSy+fMbNNVjIV+OuPOBE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
